'作成者 5345kk'
@startuml


  database DataServer as Data{

      rectangle information as info{
      usecase スコア
      usecase 体力

    }

      rectangle PlayerInformation as pinfo{
        usecase プレイヤー名
        usecase 識別ID
      }






  }

'link'
JoinServer<-pinfo
GameServer<-info
Printer->Data
Viewer->Data

'関連付け'

@enduml
