'作成者 5345kk'
@startuml

Package Gameserver{
  Class Manage{
    +void gameStart()
    +void gamePeriod()
    +void request(int playerID)
    +void changeMission(int missionID)
    +void penalty(int playerID,int mode)
  }
  note left:メッセに応じて実行する

  Class Penalty{
    +void hit(int playerID)
    +void beHit(int playerID)
    +void hpZero(int playerID)
    +void changeStatus(int playerID)
    +void score(int playerID)
  }
  note left:罰を含めた状態変化をペナルティとする

  Class Rmessage{
    +void recieveMes()
    +void decodeMes()
  }
  note right:要求を受け取る

  Class Smessage{
    +void sendMes(Status)
  }

  Class Status{
    +void getStatus(int playerID)
  }
  note left:ゲーム終了時にプレイヤーからステータスを回収

  Class Data{
    +void encodeData(Status)
  }
  note right:プレイヤーのデータをSQLに変換して送信する
}

Package CLIENT <<node>>{
}
Package PLAYER <<node>>{
}
Package DATABASE <<node>>{
}



CLIENT"1"-->"1"Rmessage

Rmessage<.left>Manage
Smessage<.right>Data
Smessage"1" <-> "0..*"PLAYER

Status ..>Smessage

Manage ..>Penalty
Manage ..up> Status

Penalty ..> Smessage

Data"1"<->"1"DATABASE

@enduml
