@startuml
'設計者　川上　輝'

'文字方向を指定'
'left to right direction'
'イベント要因を列挙'
actor 参加者 as Player
actor 通信 as Transmit
'動作を規定'
package  RaspberryPi(Player) as Raspi {
  rectangle 場面管理 as SceneAction {
    rectangle ゲーム状態 as GameStatus{
      rectangle ゲーム中 as Gaming{
        [ミッション] as Mission
        [通常] as Normal
        Mission <.> Normal
      }
      rectangle 準備中 as Standby {
        [説明] as Introduction
        [何もしない] as Nothing
        Introduction<.> Nothing
      }
      Gaming <.> Standby
      }
      (シーン変更)as ChangeScene
      ChangeScene -> GameStatus
      Transmit -> ChangeScene
  }
  'ユーザーからのイベント'
  rectangle 行動管理 as GamingAction{
    usecase 撃つ as Hit
    usecase アイテムをとる as GetItem
    usecase 撃たれる as GetDamege
  }
  Gaming .>GamingAction
  Player ->GamingAction
  GamingAction -> Transmit

  usecase 状態を表示する as ViewStatus
  }
'プレーヤの動作について'


@enduml
