'作成者 5345kk'
@startuml

class Printer{
  Paper
  Ink

  resultPrint()
  getTranslationDate() '解析したデータを受け取る'
}
class Reader{
translationDate()
getDate() '生成したデータを受け取る'
}

class "CreateDate?(Yamamura)" {

}
class Player{
ID

getResult()
}

class "ParsonofPrint"{
  pushButton() '印刷期のボタンを押す'

}

'link'
Printer - Reader
Reader - "CreateDate?(Yamamura)"
Printer -down- Player
Printer -up- "ParsonofPrint"

@enduml
